apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
  namespace: mani-ns
spec:
  type: NodePort  # Use NodePort if LoadBalancer is not supported
  ports:
    - port: 3130          # Service port (internal)
      targetPort: 3130    # Container port
      nodePort: 30080     # External port (browser)
      protocol: TCP

  selector:
    app: userprofile
